### ISSUE TITLE
Stretch bubble and input box

### ISSUE THREAD

**Issue by capem** [m1kethai/userstyle__stretchgemini#1]
```css
/* ==UserStyle==
@name         StretchGemini - Resizable chat UI width for Gemini
@author       m1kethai (modified)
@description  A set of configurable presets for expanding the width of Gemini's main chat view, input box, and user query, plus some extra toggles for hiding certain elements & other UI enhancements.
@version      2.3.0
@namespace    https://userstyles.world/style/21358/stretchgemini-resizable-chat-ui-width-for-gemini
@preprocessor less
@var select   stretchFactor "🧘 Chat view width preset" {
    "⛔ None":               "0",
    "🤏 Some breathing room": "1",
    "🙆 Pretty relaxed":      "2",
    "✨ Spacious*":           "3",
    "🙌 Unbounded":           "4"
}
@var checkbox enableBonusFeatures "👇 Enable bonus UI enhancements below 👇" 0
@var checkbox hideDisclaimer      "⚠️ Hide disclaimer" 1
@var checkbox hideAvatar          "🙈 Hide Gemini chat avatar" 1
==/UserStyle== */

@-moz-document domain("gemini.google.com") {
    html {
        /* ===== EXPAND CHAT UI ===== */
        .expandChatUI() when (@stretchFactor >=1) {
            @defaultMw: 760px;
            @widthMultiplier:
                if((@stretchFactor =1), 1.33,
                if((@stretchFactor =2), 1.66,
                if((@stretchFactor =3), 2.0, null
            )));
            @adjustedMw: if(
                (isnumber(@widthMultiplier)),
                (@defaultMw*@widthMultiplier),
                unset
            );
            max-width: @adjustedMw;
        }

        /* * Apply width expansion to all relevant containers
         */
        div.conversation-container,
        div.input-area-container,
        .user-query-bubble-with-background {
            .expandChatUI() !important;
        }

        & when (@enableBonusFeatures =1) {
            /* ===== HIDE DISCLAIMER ===== */
            div.input-area-container when(@hideDisclaimer =1) {
                ~ hallucination-disclaimer {
                    display: none !important;
                }
                padding-bottom: 0.5rem;
            }

            /* ===== HIDE GEMINI AVATARS ===== */
            div.avatar-gutter when(@hideAvatar =1) {
                display: none !important;
            }
        }
    }
}
```
